name: my workflow
on:
  push:
    branches:
    - main
    - preprod
    - staging
  workflow_dispatch:
env:
  CLUSTER_NAME: format('{0}_CLUSTER_NAME', ${{ github.ref_name }})
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo $CLUSTER_NAME
